const books = [
  {
    id: 1,
    author: 'J.K. Rowling',
    title: "Harry Potter and the Sorcerer's Stone",
    year: 1997,
    publisher: 'Scholastic',
    genre: 'Fantasy',
    awards: ['British Book Award', "Children's Book Award"],
    netRevenue: 250000000,
  },
  {
    id: 2,
    author: 'George Orwell',
    title: '1984',
    year: 1949,
    publisher: 'Secker & Warburg',
    genre: 'Dystopian',
    awards: ['Prometheus Hall of Fame Award'],
    netRevenue: 15000000,
  },
  {
    id: 3,
    author: 'Jane Austen',
    title: 'Pride and Prejudice',
    year: 1813,
    publisher: 'T. Egerton',
    genre: 'Romance',
    awards: [],
    netRevenue: 500000,
  },
  {
    id: 4,
    author: 'F. Scott Fitzgerald',
    title: 'The Great Gatsby',
    year: 1925,
    publisher: "Charles Scribner's Sons",
    genre: 'Classic',
    awards: ["Time's All-Time 100 Novels"],
    netRevenue: 8000000,
  },
  {
    id: 5,
    author: 'Gabriel García Márquez',
    title: 'One Hundred Years of Solitude',
    year: 1967,
    publisher: 'Harper & Row',
    genre: 'Magic Realism',
    awards: ['Nobel Prize in Literature'],
    netRevenue: 12000000,
  },
];

module.exports = { books };
